# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/

    The version of the OpenAPI document: VERSION
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr
from pydantic import Field
from argo_workflows.models.bitbucket_server_repository import BitbucketServerRepository
from argo_workflows.models.event_source_filter import EventSourceFilter
from argo_workflows.models.secret_key_selector import SecretKeySelector
from argo_workflows.models.webhook_context import WebhookContext
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BitbucketServerEventSource(BaseModel):
    """
    BitbucketServerEventSource
    """ # noqa: E501
    access_token: Optional[SecretKeySelector] = Field(default=None, alias="accessToken")
    bitbucketserver_base_url: Optional[StrictStr] = Field(default=None, alias="bitbucketserverBaseURL")
    delete_hook_on_finish: Optional[StrictBool] = Field(default=None, alias="deleteHookOnFinish")
    events: Optional[List[StrictStr]] = None
    filter: Optional[EventSourceFilter] = None
    metadata: Optional[Dict[str, StrictStr]] = None
    project_key: Optional[StrictStr] = Field(default=None, alias="projectKey")
    repositories: Optional[List[BitbucketServerRepository]] = None
    repository_slug: Optional[StrictStr] = Field(default=None, alias="repositorySlug")
    webhook: Optional[WebhookContext] = None
    webhook_secret: Optional[SecretKeySelector] = Field(default=None, alias="webhookSecret")
    __properties: ClassVar[List[str]] = ["accessToken", "bitbucketserverBaseURL", "deleteHookOnFinish", "events", "filter", "metadata", "projectKey", "repositories", "repositorySlug", "webhook", "webhookSecret"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BitbucketServerEventSource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of access_token
        if self.access_token:
            _dict['accessToken'] = self.access_token.to_dict()
        # override the default output from pydantic by calling `to_dict()` of filter
        if self.filter:
            _dict['filter'] = self.filter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in repositories (list)
        _items = []
        if self.repositories:
            for _item in self.repositories:
                if _item:
                    _items.append(_item.to_dict())
            _dict['repositories'] = _items
        # override the default output from pydantic by calling `to_dict()` of webhook
        if self.webhook:
            _dict['webhook'] = self.webhook.to_dict()
        # override the default output from pydantic by calling `to_dict()` of webhook_secret
        if self.webhook_secret:
            _dict['webhookSecret'] = self.webhook_secret.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BitbucketServerEventSource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accessToken": SecretKeySelector.from_dict(obj.get("accessToken")) if obj.get("accessToken") is not None else None,
            "bitbucketserverBaseURL": obj.get("bitbucketserverBaseURL"),
            "deleteHookOnFinish": obj.get("deleteHookOnFinish"),
            "events": obj.get("events"),
            "filter": EventSourceFilter.from_dict(obj.get("filter")) if obj.get("filter") is not None else None,
            "metadata": obj.get("metadata"),
            "projectKey": obj.get("projectKey"),
            "repositories": [BitbucketServerRepository.from_dict(_item) for _item in obj.get("repositories")] if obj.get("repositories") is not None else None,
            "repositorySlug": obj.get("repositorySlug"),
            "webhook": WebhookContext.from_dict(obj.get("webhook")) if obj.get("webhook") is not None else None,
            "webhookSecret": SecretKeySelector.from_dict(obj.get("webhookSecret")) if obj.get("webhookSecret") is not None else None
        })
        return _obj


