# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/

    The version of the OpenAPI document: VERSION
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from argo_workflows.models.data_filter import DataFilter
from argo_workflows.models.event_context import EventContext
from argo_workflows.models.expr_filter import ExprFilter
from argo_workflows.models.time_filter import TimeFilter
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EventDependencyFilter(BaseModel):
    """
    EventDependencyFilter defines filters and constraints for a 
    """ # noqa: E501
    context: Optional[EventContext] = None
    data: Optional[List[DataFilter]] = None
    data_logical_operator: Optional[StrictStr] = Field(default=None, description="DataLogicalOperator defines how multiple Data filters (if defined) are evaluated together. Available values: and (&&), or (||) Is optional and if left blank treated as and (&&).", alias="dataLogicalOperator")
    expr_logical_operator: Optional[StrictStr] = Field(default=None, description="ExprLogicalOperator defines how multiple Exprs filters (if defined) are evaluated together. Available values: and (&&), or (||) Is optional and if left blank treated as and (&&).", alias="exprLogicalOperator")
    exprs: Optional[List[ExprFilter]] = Field(default=None, description="Exprs contains the list of expressions evaluated against the event payload.")
    script: Optional[StrictStr] = Field(default=None, description="Script refers to a Lua script evaluated to determine the validity of an ")
    time: Optional[TimeFilter] = None
    __properties: ClassVar[List[str]] = ["context", "data", "dataLogicalOperator", "exprLogicalOperator", "exprs", "script", "time"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventDependencyFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context
        if self.context:
            _dict['context'] = self.context.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item in self.data:
                if _item:
                    _items.append(_item.to_dict())
            _dict['data'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in exprs (list)
        _items = []
        if self.exprs:
            for _item in self.exprs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['exprs'] = _items
        # override the default output from pydantic by calling `to_dict()` of time
        if self.time:
            _dict['time'] = self.time.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EventDependencyFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "context": EventContext.from_dict(obj.get("context")) if obj.get("context") is not None else None,
            "data": [DataFilter.from_dict(_item) for _item in obj.get("data")] if obj.get("data") is not None else None,
            "dataLogicalOperator": obj.get("dataLogicalOperator"),
            "exprLogicalOperator": obj.get("exprLogicalOperator"),
            "exprs": [ExprFilter.from_dict(_item) for _item in obj.get("exprs")] if obj.get("exprs") is not None else None,
            "script": obj.get("script"),
            "time": TimeFilter.from_dict(obj.get("time")) if obj.get("time") is not None else None
        })
        return _obj


