# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/

    The version of the OpenAPI document: VERSION
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from argo_workflows.models.counter import Counter
from argo_workflows.models.gauge import Gauge
from argo_workflows.models.histogram import Histogram
from argo_workflows.models.metric_label import MetricLabel
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Prometheus(BaseModel):
    """
    Prometheus is a prometheus metric to be emitted
    """ # noqa: E501
    counter: Optional[Counter] = None
    gauge: Optional[Gauge] = None
    help: StrictStr = Field(description="Help is a string that describes the metric")
    histogram: Optional[Histogram] = None
    labels: Optional[List[MetricLabel]] = Field(default=None, description="Labels is a list of metric labels")
    name: StrictStr = Field(description="Name is the name of the metric")
    when: Optional[StrictStr] = Field(default=None, description="When is a conditional statement that decides when to emit the metric")
    __properties: ClassVar[List[str]] = ["counter", "gauge", "help", "histogram", "labels", "name", "when"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Prometheus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of counter
        if self.counter:
            _dict['counter'] = self.counter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gauge
        if self.gauge:
            _dict['gauge'] = self.gauge.to_dict()
        # override the default output from pydantic by calling `to_dict()` of histogram
        if self.histogram:
            _dict['histogram'] = self.histogram.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item in self.labels:
                if _item:
                    _items.append(_item.to_dict())
            _dict['labels'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Prometheus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "counter": Counter.from_dict(obj.get("counter")) if obj.get("counter") is not None else None,
            "gauge": Gauge.from_dict(obj.get("gauge")) if obj.get("gauge") is not None else None,
            "help": obj.get("help"),
            "histogram": Histogram.from_dict(obj.get("histogram")) if obj.get("histogram") is not None else None,
            "labels": [MetricLabel.from_dict(_item) for _item in obj.get("labels")] if obj.get("labels") is not None else None,
            "name": obj.get("name"),
            "when": obj.get("when")
        })
        return _obj


