# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/

    The version of the OpenAPI document: VERSION
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr
from pydantic import Field
from argo_workflows.models.metadata import Metadata
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WorkflowLevelArtifactGC(BaseModel):
    """
    WorkflowLevelArtifactGC describes how to delete artifacts from completed Workflows - this spec is used on the Workflow level
    """ # noqa: E501
    force_finalizer_removal: Optional[StrictBool] = Field(default=None, description="ForceFinalizerRemoval: if set to true, the finalizer will be removed in the case that Artifact GC fails", alias="forceFinalizerRemoval")
    pod_metadata: Optional[Metadata] = Field(default=None, alias="podMetadata")
    pod_spec_patch: Optional[StrictStr] = Field(default=None, description="PodSpecPatch holds strategic merge patch to apply against the artgc pod spec.", alias="podSpecPatch")
    service_account_name: Optional[StrictStr] = Field(default=None, description="ServiceAccountName is an optional field for specifying the Service Account that should be assigned to the Pod doing the deletion", alias="serviceAccountName")
    strategy: Optional[StrictStr] = Field(default=None, description="Strategy is the strategy to use.")
    __properties: ClassVar[List[str]] = ["forceFinalizerRemoval", "podMetadata", "podSpecPatch", "serviceAccountName", "strategy"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkflowLevelArtifactGC from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pod_metadata
        if self.pod_metadata:
            _dict['podMetadata'] = self.pod_metadata.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WorkflowLevelArtifactGC from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "forceFinalizerRemoval": obj.get("forceFinalizerRemoval"),
            "podMetadata": Metadata.from_dict(obj.get("podMetadata")) if obj.get("podMetadata") is not None else None,
            "podSpecPatch": obj.get("podSpecPatch"),
            "serviceAccountName": obj.get("serviceAccountName"),
            "strategy": obj.get("strategy")
        })
        return _obj


